[33m8353588[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mfeature-branch2[m[33m, [m[1;31morigin/seungho[m[33m, [m[1;32mseungho[m[33m, [m[1;32mfeature-branch[m[33m)[m HEAD@{0}: checkout: moving from feature-branch to feature-branch2
[33m8353588[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mfeature-branch2[m[33m, [m[1;31morigin/seungho[m[33m, [m[1;32mseungho[m[33m, [m[1;32mfeature-branch[m[33m)[m HEAD@{1}: checkout: moving from seungho to feature-branch
[33m8353588[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mfeature-branch2[m[33m, [m[1;31morigin/seungho[m[33m, [m[1;32mseungho[m[33m, [m[1;32mfeature-branch[m[33m)[m HEAD@{2}: checkout: moving from merge to seungho
[33m8f6dfae[m[33m ([m[1;31morigin/namhee[m[33m, [m[1;31morigin/merge[m[33m, [m[1;32mmerge[m[33m)[m HEAD@{3}: checkout: moving from seungho to merge
[33mf7a6d8e[m HEAD@{4}: reset: moving to f7a6d8e
[33mf7a6d8e[m HEAD@{5}: reset: moving to f7a6d8e
[33mf7a6d8e[m HEAD@{6}: commit (merge): Merge remote-tracking branch 'origin/merge' into seungho
[33m8353588[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mfeature-branch2[m[33m, [m[1;31morigin/seungho[m[33m, [m[1;32mseungho[m[33m, [m[1;32mfeature-branch[m[33m)[m HEAD@{7}: checkout: moving from merge to seungho
[33m8f6dfae[m[33m ([m[1;31morigin/namhee[m[33m, [m[1;31morigin/merge[m[33m, [m[1;32mmerge[m[33m)[m HEAD@{8}: checkout: moving from seungho to merge
[33m8353588[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mfeature-branch2[m[33m, [m[1;31morigin/seungho[m[33m, [m[1;32mseungho[m[33m, [m[1;32mfeature-branch[m[33m)[m HEAD@{9}: commit: 전체공고 xml 만들기
[33mc414649[m HEAD@{10}: checkout: moving from leedj to seungho
[33m3d3ada0[m[33m ([m[1;31morigin/leedj[m[33m, [m[1;32mleedj[m[33m)[m HEAD@{11}: checkout: moving from seungho to leedj
[33mc414649[m HEAD@{12}: reset: moving to HEAD
[33mc414649[m HEAD@{13}: commit: 세션 로직 수정
[33m56552f1[m HEAD@{14}: commit: login session 연결
[33m4f3e065[m HEAD@{15}: commit: 로그인은 성공
[33m86e5d2e[m HEAD@{16}: checkout: moving from main to seungho
[33mb9178c6[m HEAD@{17}: reset: moving to HEAD
[33mb9178c6[m HEAD@{18}: checkout: moving from seungho to main
[33m86e5d2e[m HEAD@{19}: commit: make sign up
[33m3b3bd4f[m HEAD@{20}: merge main: Merge made by the 'ort' strategy.
[33m41a292f[m HEAD@{21}: commit: commit test
[33m27e3ecd[m HEAD@{22}: checkout: moving from main to seungho
[33mb9178c6[m HEAD@{23}: checkout: moving from seungho to main
[33m27e3ecd[m HEAD@{24}: checkout: moving from main to seungho
[33mb9178c6[m HEAD@{25}: checkout: moving from seungho to main
[33m27e3ecd[m HEAD@{26}: commit: test-commit
[33m4bb80f5[m HEAD@{27}: commit: commit test - seungho
[33m4d58ed1[m HEAD@{28}: checkout: moving from main to seungho
[33m4d58ed1[m HEAD@{29}: clone: from https://github.com/Rookies23-nomer-hacker/albbamon_mobile.git
